# Generated by Django 5.2.6 on 2025-11-17 21:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código ISO (USD, EUR, CLP)', max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(blank=True, max_length=10)),
                ('tasa_cambio_usd', models.DecimalField(decimal_places=6, help_text='Tasa respecto a USD', max_digits=15)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'db_table': 'api_divisas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('iniciado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga Masiva',
                'verbose_name_plural': 'Cargas Masivas',
                'db_table': 'api_cargas_masivas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor_dueno', models.CharField(blank=True, max_length=255)),
                ('rut_es_el_manual', models.CharField(blank=True, max_length=12)),
                ('ano_comercial', models.CharField(blank=True, max_length=50)),
                ('mercado', models.CharField(blank=True, max_length=50)),
                ('instrumento', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, null=True)),
                ('numero_dividendo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo_sociedad', models.CharField(blank=True, max_length=10)),
                ('divisa', models.CharField(default='CLP', max_length=10)),
                ('acopio_lsfxf', models.BooleanField(default=False)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('valor_convertido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('factor_8', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_9', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_10', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_11', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_12', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_13', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_14', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_15', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_16', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_17', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_18', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_19', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_20', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_21', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_22', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_23', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_24', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_25', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_26', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_27', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_28', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_29', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_30', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_31', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_32', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_33', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_34', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_35', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_36', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_37', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('es_local', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_tributarias', to=settings.AUTH_USER_MODEL)),
                ('carga_masiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_tributarias', to='api.cargamasiva')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('READ', 'Leer'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión')], db_index=True, max_length=20)),
                ('modelo', models.CharField(help_text='Modelo afectado', max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes del cambio', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después del cambio', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'api_logs_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('CARGA', 'Carga')], max_length=50)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_operacion', to='api.calificaciontributaria')),
                ('carga_masiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_operacion', to='api.cargamasiva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Operación',
                'verbose_name_plural': 'Logs de Operación',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(db_index=True, help_text='Nombre de la entidad calificada', max_length=200)),
                ('tipo_calificacion', models.CharField(choices=[('AAA', 'AAA - Máxima Calidad'), ('AA', 'AA - Alta Calidad'), ('A', 'A - Calidad Media-Alta'), ('BBB', 'BBB - Calidad Media'), ('BB', 'BB - Especulativo'), ('B', 'B - Altamente Especulativo'), ('CCC', 'CCC - Riesgo Sustancial'), ('CC', 'CC - Muy Alto Riesgo'), ('C', 'C - Riesgo Extremo'), ('D', 'D - Default')], db_index=True, help_text='Tipo de calificación crediticia', max_length=10)),
                ('puntaje', models.DecimalField(decimal_places=2, help_text='Puntaje numérico de 0 a 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_calificacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de la calificación')),
                ('agencia_calificadora', models.CharField(help_text='Agencia que emitió la calificación', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Estado de la calificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'api_calificaciones',
                'ordering': ['-fecha_calificacion'],
                'indexes': [models.Index(fields=['entidad', 'fecha_calificacion'], name='api_calific_entidad_be9151_idx'), models.Index(fields=['tipo_calificacion', 'activo'], name='api_calific_tipo_ca_1daf9f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('puntaje__gte', 0), ('puntaje__lte', 100)), name='puntaje_rango_valido'), models.UniqueConstraint(fields=('entidad', 'agencia_calificadora', 'fecha_calificacion'), name='calificacion_unica_por_entidad_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='cargamasiva',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='api_cargas__estado_19de39_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'timestamp'], name='api_logs_au_usuario_bb6a62_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', 'modelo'], name='api_logs_au_accion_b8e3af_idx'),
        ),
    ]
