# Generated by Django 5.2.6 on 2025-11-18 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargamasiva',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.RemoveIndex(
            model_name='cargamasiva',
            name='api_cargas__estado_19de39_idx',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='mensaje_error',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='total_registros',
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='mercado',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('INTERNACIONAL', 'Internacional')], default='LOCAL', max_length=50),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='tipo_carga',
            field=models.CharField(choices=[('FACTORES', 'Factores'), ('MONITOR', 'Monitor')], default='FACTORES', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='archivo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='iniciado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AlterModelTable(
            name='cargamasiva',
            table='carga_masiva',
        ),
    ]
