# Generated by Django 5.2.6 on 2025-11-18 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cargamasiva_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargamasiva',
            name='iniciado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
    ]
