# Generated by Django 5.2.8 on 2025-11-19 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cargamasiva_iniciado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['usuario', '-created_at'], name='cal_trib_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['mercado', 'divisa'], name='cal_trib_merc_div_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['instrumento', '-fecha_pago'], name='cal_trib_inst_pago_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['corredor_dueno', 'mercado'], name='cal_trib_corr_merc_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['-fecha_pago', 'divisa'], name='cal_trib_pago_div_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['tipo_sociedad', 'es_local'], name='cal_trib_soc_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['carga_masiva', '-created_at'], name='cal_trib_carga_idx'),
        ),
        migrations.AddConstraint(
            model_name='calificaciontributaria',
            constraint=models.CheckConstraint(condition=models.Q(('valor_historico__gte', 0), ('valor_historico__isnull', True), _connector='OR'), name='valor_historico_positivo'),
        ),
        migrations.AddConstraint(
            model_name='calificaciontributaria',
            constraint=models.CheckConstraint(condition=models.Q(('valor_convertido__gte', 0), ('valor_convertido__isnull', True), _connector='OR'), name='valor_convertido_positivo'),
        ),
    ]
