# Generated by Django 5.2.8 on 2025-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calificaciontributaria_cal_trib_user_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasiva',
            name='errores_detalle',
            field=models.JSONField(blank=True, default=list, help_text='Detalle de errores por fila'),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='progreso',
            field=models.IntegerField(default=0, help_text='Porcentaje de progreso (0-100)'),
        ),
    ]
