# Generated by Django 5.2.6 on 2025-10-08 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carga', models.CharField(choices=[('FACTORES', 'Factores'), ('MONITOR', 'Monitor')], max_length=50)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('errores_detalle', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor_dueno', models.CharField(blank=True, max_length=255)),
                ('rut_es_el_manual', models.CharField(blank=True, max_length=12)),
                ('ano_comercial', models.CharField(blank=True, max_length=50)),
                ('mercado', models.CharField(blank=True, max_length=50)),
                ('instrumento', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, null=True)),
                ('numero_dividendo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo_sociedad', models.CharField(blank=True, max_length=10)),
                ('acopio_lsfxf', models.BooleanField(default=False)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_8', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_9', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_10', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_11', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_12', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_13', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_14', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_15', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_16', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_17', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_18', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_19', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_20', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_21', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_22', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_23', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_24', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_25', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_26', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_27', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_28', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_29', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_30', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_31', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_32', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_33', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_34', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_35', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_36', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('factor_37', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('es_local', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carga_masiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cargamasiva')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('CARGA', 'Carga')], max_length=50)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.calificaciontributaria')),
                ('carga_masiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cargamasiva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
