# Generated by Django 5.2.6 on 2025-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_nombre_completo_perfil_rut_cargamasiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='divisa',
            field=models.CharField(default='CLP', max_length=10),
        ),
    ]
