# Generated by Django 5.2.6 on 2025-10-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_calificaciontributaria_divisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='moneda',
            field=models.CharField(default='CLP', max_length=10),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='valor_convertido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
