# Generated by Django 5.2.6 on 2025-10-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_calificaciontributaria_moneda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='moneda',
        ),
    ]
