# Generated by Django 5.2.6 on 2025-11-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_calificaciontributaria_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoperacion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='logoperacion',
            name='carga_masiva',
        ),
        migrations.RemoveField(
            model_name='logoperacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CalificacionTributaria',
        ),
        migrations.DeleteModel(
            name='CargaMasiva',
        ),
        migrations.DeleteModel(
            name='LogOperacion',
        ),
    ]
